using System;
using System.Collections.Generic;

#nullable disable

namespace APCore.Models
{
    public partial class _CrewsJSON
    {
        public string record { get; set; }
        public string Id { get; set; }
        public string PID { get; set; }
        public string BaseAirportId { get; set; }
        public string BaseAirport { get; set; }
        public string CurrentLocationAirport { get; set; }
        public string CurrentLocationCity { get; set; }
        public string CurrentLocationCityId { get; set; }
        public string DateJoinCompany { get; set; }
        public string ExpCompany { get; set; }
        public string IsActive { get; set; }
        public string DateRegister { get; set; }
        public string DateConfirmed { get; set; }
        public string IsDeleted { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string CustomerId { get; set; }
        public string GroupId { get; set; }
        public string JobGroup { get; set; }
        public string JobGroupCode { get; set; }
        public string JobGroupRoot { get; set; }
        public string MarriageId { get; set; }
        public string NID { get; set; }
        public string SexId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Name { get; set; }
        public string DateBirth { get; set; }
        public string Email { get; set; }
        public string Phone1 { get; set; }
        public string Phone2 { get; set; }
        public string Mobile { get; set; }
        public string FaxTelNumber { get; set; }
        public string PassportNumber { get; set; }
        public string DatePassportIssue { get; set; }
        public string DatePassportExpire { get; set; }
        public string Address { get; set; }
        public string DateJoinAvation { get; set; }
        public string Exp { get; set; }
        public string DateLastCheckUP { get; set; }
        public string DateNextCheckUP { get; set; }
        public string DateYearOfExperience { get; set; }
        public string CaoCardNumber { get; set; }
        public string DateCaoCardIssue { get; set; }
        public string DateCaoCardExpire { get; set; }
        public string CompetencyNo { get; set; }
        public string CaoInterval { get; set; }
        public string CaoIntervalCalanderTypeId { get; set; }
        public string Remark { get; set; }
        public string StampNumber { get; set; }
        public string StampUrl { get; set; }
        public string TechLogNo { get; set; }
        public string DateIssueNDT { get; set; }
        public string IntervalNDT { get; set; }
        public string NDTNumber { get; set; }
        public string NDTIntervalCalanderTypeId { get; set; }
        public string Nickname { get; set; }
        public string CityId { get; set; }
        public string FatherName { get; set; }
        public string IDNo { get; set; }
        public string UserId { get; set; }
        public string ImageUrl { get; set; }
        public string CustomerCreatorId { get; set; }
        public string Age { get; set; }
        public string LocationId { get; set; }
        public string OrgRoleId { get; set; }
        public string LocationPhone { get; set; }
        public string IsMainLocation { get; set; }
        public string MaritalStatus { get; set; }
        public string Sex { get; set; }
        public string CaoIntervalCalanderType { get; set; }
        public string NDTIntervalCalanderType { get; set; }
        public string City { get; set; }
        public string StateId { get; set; }
        public string State { get; set; }
        public string CountryId { get; set; }
        public string Country { get; set; }
        public string CityFullName { get; set; }
        public string Customer { get; set; }
        public string Location { get; set; }
        public string RootLocation { get; set; }
        public string LocationCode { get; set; }
        public string PersonId { get; set; }
        public string EmployeeLocationId { get; set; }
        public string Post { get; set; }
        public string RemainNDT { get; set; }
        public string RemainCAO { get; set; }
        public string RemainPassport { get; set; }
        public string IsNDTExpired { get; set; }
        public string IsNDTExpiring { get; set; }
        public string IsCAOExpired { get; set; }
        public string IsCAOExpiring { get; set; }
        public string IsMedicalExpiring { get; set; }
        public string IsPassportExpired { get; set; }
        public string IsPassportExpiring { get; set; }
        public string DateExpireNDT { get; set; }
        public string CriticalCertificatesCount { get; set; }
        public string BookAlert { get; set; }
        public string Types { get; set; }
        public string ProficiencyExpireDate { get; set; }
        public string CrewMemberCertificateExpireDate { get; set; }
        public string LicenceExpireDate { get; set; }
        public string LicenceIRExpireDate { get; set; }
        public string SimulatorLastCheck { get; set; }
        public string SimulatorNextCheck { get; set; }
        public string RampPassNo { get; set; }
        public string RampPassExpireDate { get; set; }
        public string LanguageCourseExpireDate { get; set; }
        public string LicenceTitle { get; set; }
        public string LicenceInitialIssue { get; set; }
        public string RaitingCertificates { get; set; }
        public string LicenceIssueDate { get; set; }
        public string LicenceDescription { get; set; }
        public string ProficiencyCheckType { get; set; }
        public string ProficiencyCheckDate { get; set; }
        public string ProficiencyValidUntil { get; set; }
        public string ProficiencyDescriptionOPC { get; set; }
        public string ProficiencyCheckDateOPC { get; set; }
        public string ProficiencyValidUntilOPC { get; set; }
        public string DateTRIExpired { get; set; }
        public string DateTREExpired { get; set; }
        public string ICAOLPRLevel { get; set; }
        public string ICAOLPRValidUntil { get; set; }
        public string MedicalClass { get; set; }
        public string PostalCode { get; set; }
        public string MedicalLimitation { get; set; }
        public string ProficiencyDescription { get; set; }
        public string VisaExpireDate { get; set; }
        public string SEPTIssueDate { get; set; }
        public string SEPTExpireDate { get; set; }
        public string SEPTPIssueDate { get; set; }
        public string SEPTPExpireDate { get; set; }
        public string DangerousGoodsIssueDate { get; set; }
        public string DangerousGoodsExpireDate { get; set; }
        public string CCRMIssueDate { get; set; }
        public string CCRMExpireDate { get; set; }
        public string CRMIssueDate { get; set; }
        public string CRMExpireDate { get; set; }
        public string SMSIssueDate { get; set; }
        public string SMSExpireDate { get; set; }
        public string AviationSecurityIssueDate { get; set; }
        public string AviationSecurityExpireDate { get; set; }
        public string EGPWSIssueDate { get; set; }
        public string EGPWSExpireDate { get; set; }
        public string UpsetRecoveryTrainingIssueDate { get; set; }
        public string UpsetRecoveryTrainingExpireDate { get; set; }
        public string ColdWeatherOperationIssueDate { get; set; }
        public string HotWeatherOperationIssueDate { get; set; }
        public string ColdWeatherOperationExpireDate { get; set; }
        public string HotWeatherOperationExpireDate { get; set; }
        public string FirstAidIssueDate { get; set; }
        public string FirstAidExpireDate { get; set; }
        public string PBNRNAVIssueDate { get; set; }
        public string PBNRNAVExpireDate { get; set; }
        public string RemainFirstAid { get; set; }
        public string IsFirstAidExpired { get; set; }
        public string RemainCMC { get; set; }
        public string IsCMCExpired { get; set; }
        public string RemainLicence { get; set; }
        public string IsLicenceExpired { get; set; }
        public string RemainLicenceIR { get; set; }
        public string IsLicenceIRExpired { get; set; }
        public string RemainProficiency { get; set; }
        public string IsProficiencyExpired { get; set; }
        public string RemainProficiencyOPC { get; set; }
        public string IsProficiencyOPCExpired { get; set; }
        public string RemainLPR { get; set; }
        public string IsLPRExpired { get; set; }
        public string RemainMedical { get; set; }
        public string IsMedicalExpired { get; set; }
        public string RemainSEPT { get; set; }
        public string IsSEPTExpired { get; set; }
        public string RemainSEPTP { get; set; }
        public string IsSEPTPExpired { get; set; }
        public string RemainDG { get; set; }
        public string IsDGExpired { get; set; }
        public string RemainCRM { get; set; }
        public string IsCRMExpired { get; set; }
        public string RemainCCRM { get; set; }
        public string IsCCRMExpired { get; set; }
        public string RemainSMS { get; set; }
        public string IsSMSExpired { get; set; }
        public string RemainAvSec { get; set; }
        public string IsAvSecExpired { get; set; }
        public string RemainUpsetRecoveryTraining { get; set; }
        public string IsUpsetRecoveryTrainingExpired { get; set; }
        public string RemainColdWeather { get; set; }
        public string IsColdWeatherExpired { get; set; }
        public string RemainHotWeather { get; set; }
        public string IsHotWeatherExpired { get; set; }
        public string ScheduleName { get; set; }
        public string Code { get; set; }
        public string DateInactiveBegin { get; set; }
        public string DateInactiveEnd { get; set; }
        public string LinkedIn { get; set; }
        public string Telegram { get; set; }
        public string WhatsApp { get; set; }
        public string AircraftTypeId { get; set; }
        public string DateTypeIssue { get; set; }
        public string DateTypeExpire { get; set; }
        public string TypeRemain { get; set; }
        public string LineIssueDate { get; set; }
        public string LineExpireDate { get; set; }
        public string RecurrentIssueDate { get; set; }
        public string RecurrentExpireDate { get; set; }
        public string IsRecurrentExpired { get; set; }
        public string IsLineExpired { get; set; }
        public string IsTRIExpired { get; set; }
        public string IsTREExpired { get; set; }
        public string RemainTRI { get; set; }
        public string RemainTRE { get; set; }
        public string RemainRecurrent { get; set; }
        public string RemainLine { get; set; }
        public string FlightSum { get; set; }
        public string FlightEarly { get; set; }
        public string FlightLate { get; set; }
        public string InActive { get; set; }
    }
}
