using System;
using System.Collections.Generic;

#nullable disable

namespace APCore.Models
{
    public partial class ViewCrew
    {
        public int Id { get; set; }
        public string ImageUrl { get; set; }
        public string PID { get; set; }
        public int PersonId { get; set; }
        public DateTime? DateJoinCompany { get; set; }
        public int? ExpCompany { get; set; }
        public DateTime? DateRegister { get; set; }
        public bool IsActive { get; set; }
        public DateTime? DateConfirmed { get; set; }
        public bool IsDeleted { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public int? CustomerId { get; set; }
        public int? GroupId { get; set; }
        public string JobGroup { get; set; }
        public string JobGroupCode { get; set; }
        public int MarriageId { get; set; }
        public string NID { get; set; }
        public int SexId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Name { get; set; }
        public DateTime? DateBirth { get; set; }
        public string Email { get; set; }
        public string Phone1 { get; set; }
        public string Phone2 { get; set; }
        public string Mobile { get; set; }
        public string FaxTelNumber { get; set; }
        public string PassportNumber { get; set; }
        public DateTime? DatePassportIssue { get; set; }
        public DateTime? DatePassportExpire { get; set; }
        public string Address { get; set; }
        public DateTime? DateJoinAvation { get; set; }
        public int? Exp { get; set; }
        public DateTime? DateLastCheckUP { get; set; }
        public DateTime? DateNextCheckUP { get; set; }
        public DateTime? DateYearOfExperience { get; set; }
        public string CaoCardNumber { get; set; }
        public DateTime? DateCaoCardIssue { get; set; }
        public string CompetencyNo { get; set; }
        public int? CaoInterval { get; set; }
        public DateTime? DateCaoCardExpire { get; set; }
        public int IsMedicalExpired { get; set; }
        public int? BaseAirportId { get; set; }
        public int? CurrentLocationAirportId { get; set; }
        public string CurrentLocationAirporIATA { get; set; }
        public int? LastLocationId { get; set; }
        public string LastLocation { get; set; }
        public string CurrentLocationCity { get; set; }
        public int? CurrentLocationCityId { get; set; }
        public int AvStatusId { get; set; }
        public string AvStatus { get; set; }
        public int IsAvSecExpired { get; set; }
        public int IsCCRMExpired { get; set; }
        public int IsCMCExpired { get; set; }
        public int IsColdWeatherExpired { get; set; }
        public int IsCRMExpired { get; set; }
        public int IsDGExpired { get; set; }
        public int IsHotWeatherExpired { get; set; }
        public int IsLicenceExpired { get; set; }
        public int IsLicenceIRExpired { get; set; }
        public int IsLPRExpired { get; set; }
        public int IsFirstAidExpired { get; set; }
        public int? RemainFirstAid { get; set; }
        public int IsPassportExpired { get; set; }
        public int IsProficiencyExpired { get; set; }
        public int IsSEPTExpired { get; set; }
        public int IsSEPTPExpired { get; set; }
        public int IsSMSExpired { get; set; }
        public int IsUpsetRecoveryTrainingExpired { get; set; }
        public int? RemainAvSec { get; set; }
        public int? RemainCAO { get; set; }
        public int? RemainCCRM { get; set; }
        public int? RemainCMC { get; set; }
        public int? RemainColdWeather { get; set; }
        public int? RemainCRM { get; set; }
        public int? RemainDG { get; set; }
        public int? RemainHotWeather { get; set; }
        public int? RemainLicence { get; set; }
        public int? RemainLicenceIR { get; set; }
        public int? RemainLPR { get; set; }
        public int? RemainMedical { get; set; }
        public int? RemainPassport { get; set; }
        public int? RemainProficiency { get; set; }
        public int? RemainProficiencyOPC { get; set; }
        public int? RemainSEPT { get; set; }
        public int? RemainSEPTP { get; set; }
        public int? RemainSMS { get; set; }
        public int? RemainUpsetRecoveryTraining { get; set; }
        public string ScheduleName { get; set; }
        public string Code { get; set; }
        public int GroupOrder { get; set; }
        public bool? IsValid { get; set; }
        public bool? InActive { get; set; }
        public DateTime DateInactiveBegin { get; set; }
        public DateTime DateInactiveEnd { get; set; }
        public int IsCockpit { get; set; }
        public int IsCabin { get; set; }
        public int? AircraftTypeId { get; set; }
        public DateTime? DateTypeIssue { get; set; }
        public DateTime? DateTypeExpire { get; set; }
        public string ValidTypes { get; set; }
        public double FlightSum { get; set; }
        public int FlightEarly { get; set; }
        public int FlightLate { get; set; }
        public DateTime? MedicalExpired { get; set; }
        public DateTime? MedicalIssued { get; set; }
        public DateTime? CMCExpired { get; set; }
        public DateTime? SEPTExpired { get; set; }
        public DateTime? SEPTIssued { get; set; }
        public DateTime? SEPTPIssued { get; set; }
        public DateTime? SEPTPExpired { get; set; }
        public DateTime? DGExpired { get; set; }
        public DateTime? DGIssued { get; set; }
        public DateTime? CCRMIssued { get; set; }
        public DateTime? CCRMExpired { get; set; }
        public DateTime? CRMIssued { get; set; }
        public DateTime? CRMExpired { get; set; }
        public DateTime? SMSIssued { get; set; }
        public DateTime? SMSExpired { get; set; }
        public DateTime? AvSecIssued { get; set; }
        public DateTime? AvSecExpired { get; set; }
        public DateTime? ColdWXIssued { get; set; }
        public DateTime? HotWXIssued { get; set; }
        public DateTime? ColdWXExpired { get; set; }
        public DateTime? HotWXExpired { get; set; }
        public DateTime? FirstAidExpired { get; set; }
        public DateTime? FirstAidIssued { get; set; }
        public DateTime? LineIssued { get; set; }
        public DateTime? LineExpired { get; set; }
        public DateTime? RecurrentIssued { get; set; }
        public DateTime? RecurrentExpired { get; set; }
        public DateTime? TREExpired { get; set; }
        public DateTime? TRIExpired { get; set; }
        public DateTime? LPCExpired { get; set; }
        public DateTime? LPCIssued { get; set; }
        public DateTime? OPCIssued { get; set; }
        public DateTime? OPCExpired { get; set; }
        public DateTime? LPRExpired { get; set; }
        public DateTime? LicenceExpired { get; set; }
        public DateTime? LicenceIssued { get; set; }
        public int? RemainTRI { get; set; }
        public int? RemainTRE { get; set; }
        public int? RemainRecurrent { get; set; }
        public int? RemainLine { get; set; }
        public int IsRecurrentExpired { get; set; }
        public int IsLineExpired { get; set; }
        public int IsTRIExpired { get; set; }
        public int IsTREExpired { get; set; }
    }
}
