using System;
using System.Collections.Generic;

#nullable disable

namespace APCore.Models
{
    public partial class ViewEmployee
    {
        public int Id { get; set; }
        public string PID { get; set; }
        public int? BaseAirportId { get; set; }
        public string BaseAirport { get; set; }
        public int? CurrentLocationAirport { get; set; }
        public string CurrentLocationCity { get; set; }
        public int? CurrentLocationCityId { get; set; }
        public DateTime? DateJoinCompany { get; set; }
        public int? ExpCompany { get; set; }
        public bool IsActive { get; set; }
        public DateTime? DateRegister { get; set; }
        public DateTime? DateConfirmed { get; set; }
        public bool IsDeleted { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public int? CustomerId { get; set; }
        public int? GroupId { get; set; }
        public string JobGroup { get; set; }
        public string JobGroupCode { get; set; }
        public string JobGroupRoot { get; set; }
        public int MarriageId { get; set; }
        public string NID { get; set; }
        public int SexId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Name { get; set; }
        public DateTime? DateBirth { get; set; }
        public string Email { get; set; }
        public string Phone1 { get; set; }
        public string Phone2 { get; set; }
        public string Mobile { get; set; }
        public string FaxTelNumber { get; set; }
        public string PassportNumber { get; set; }
        public DateTime? DatePassportIssue { get; set; }
        public DateTime? DatePassportExpire { get; set; }
        public string Address { get; set; }
        public DateTime? DateJoinAvation { get; set; }
        public int? Exp { get; set; }
        public DateTime? DateLastCheckUP { get; set; }
        public DateTime? DateNextCheckUP { get; set; }
        public DateTime? DateYearOfExperience { get; set; }
        public string CaoCardNumber { get; set; }
        public DateTime? DateCaoCardIssue { get; set; }
        public DateTime? DateCaoCardExpire { get; set; }
        public string CompetencyNo { get; set; }
        public int? CaoInterval { get; set; }
        public int? CaoIntervalCalanderTypeId { get; set; }
        public string Remark { get; set; }
        public string StampNumber { get; set; }
        public string StampUrl { get; set; }
        public string TechLogNo { get; set; }
        public DateTime? DateIssueNDT { get; set; }
        public int? IntervalNDT { get; set; }
        public string NDTNumber { get; set; }
        public int? NDTIntervalCalanderTypeId { get; set; }
        public string Nickname { get; set; }
        public int? CityId { get; set; }
        public string FatherName { get; set; }
        public string IDNo { get; set; }
        public string UserId { get; set; }
        public string ImageUrl { get; set; }
        public int? CustomerCreatorId { get; set; }
        public int? Age { get; set; }
        public int LocationId { get; set; }
        public int? OrgRoleId { get; set; }
        public string LocationPhone { get; set; }
        public bool IsMainLocation { get; set; }
        public string MaritalStatus { get; set; }
        public string Sex { get; set; }
        public string CaoIntervalCalanderType { get; set; }
        public string NDTIntervalCalanderType { get; set; }
        public string City { get; set; }
        public int? StateId { get; set; }
        public string State { get; set; }
        public int? CountryId { get; set; }
        public string Country { get; set; }
        public string CityFullName { get; set; }
        public string Customer { get; set; }
        public string Location { get; set; }
        public int? RootLocation { get; set; }
        public string LocationCode { get; set; }
        public int PersonId { get; set; }
        public int EmployeeLocationId { get; set; }
        public string Post { get; set; }
        public int? RemainNDT { get; set; }
        public int? RemainCAO { get; set; }
        public int? RemainPassport { get; set; }
        public int IsNDTExpired { get; set; }
        public int IsNDTExpiring { get; set; }
        public int IsCAOExpired { get; set; }
        public int IsCAOExpiring { get; set; }
        public int IsMedicalExpiring { get; set; }
        public int IsPassportExpired { get; set; }
        public int IsPassportExpiring { get; set; }
        public DateTime? DateExpireNDT { get; set; }
        public int? CriticalCertificatesCount { get; set; }
        public int? BookAlert { get; set; }
        public string Types { get; set; }
        public DateTime? ProficiencyExpireDate { get; set; }
        public DateTime? CrewMemberCertificateExpireDate { get; set; }
        public DateTime? LicenceExpireDate { get; set; }
        public DateTime? LicenceIRExpireDate { get; set; }
        public DateTime? SimulatorLastCheck { get; set; }
        public DateTime? SimulatorNextCheck { get; set; }
        public string RampPassNo { get; set; }
        public DateTime? RampPassExpireDate { get; set; }
        public DateTime? LanguageCourseExpireDate { get; set; }
        public string LicenceTitle { get; set; }
        public DateTime? LicenceInitialIssue { get; set; }
        public string RaitingCertificates { get; set; }
        public DateTime? LicenceIssueDate { get; set; }
        public string LicenceDescription { get; set; }
        public int? ProficiencyCheckType { get; set; }
        public DateTime? ProficiencyCheckDate { get; set; }
        public DateTime? ProficiencyValidUntil { get; set; }
        public string ProficiencyDescriptionOPC { get; set; }
        public DateTime? ProficiencyCheckDateOPC { get; set; }
        public DateTime? ProficiencyValidUntilOPC { get; set; }
        public DateTime? DateTRIExpired { get; set; }
        public DateTime? DateTREExpired { get; set; }
        public int? ICAOLPRLevel { get; set; }
        public DateTime? ICAOLPRValidUntil { get; set; }
        public int? MedicalClass { get; set; }
        public string PostalCode { get; set; }
        public string MedicalLimitation { get; set; }
        public string ProficiencyDescription { get; set; }
        public DateTime? VisaExpireDate { get; set; }
        public DateTime? SEPTIssueDate { get; set; }
        public DateTime? SEPTExpireDate { get; set; }
        public DateTime? SEPTPIssueDate { get; set; }
        public DateTime? SEPTPExpireDate { get; set; }
        public DateTime? DangerousGoodsIssueDate { get; set; }
        public DateTime? DangerousGoodsExpireDate { get; set; }
        public DateTime? CCRMIssueDate { get; set; }
        public DateTime? CCRMExpireDate { get; set; }
        public DateTime? CRMIssueDate { get; set; }
        public DateTime? CRMExpireDate { get; set; }
        public DateTime? SMSIssueDate { get; set; }
        public DateTime? SMSExpireDate { get; set; }
        public DateTime? AviationSecurityIssueDate { get; set; }
        public DateTime? AviationSecurityExpireDate { get; set; }
        public DateTime? EGPWSIssueDate { get; set; }
        public DateTime? EGPWSExpireDate { get; set; }
        public DateTime? UpsetRecoveryTrainingIssueDate { get; set; }
        public DateTime? UpsetRecoveryTrainingExpireDate { get; set; }
        public DateTime? ColdWeatherOperationIssueDate { get; set; }
        public DateTime? HotWeatherOperationIssueDate { get; set; }
        public DateTime? ColdWeatherOperationExpireDate { get; set; }
        public DateTime? HotWeatherOperationExpireDate { get; set; }
        public DateTime? FirstAidIssueDate { get; set; }
        public DateTime? FirstAidExpireDate { get; set; }
        public DateTime? PBNRNAVIssueDate { get; set; }
        public DateTime? PBNRNAVExpireDate { get; set; }
        public int? RemainFirstAid { get; set; }
        public int IsFirstAidExpired { get; set; }
        public int? RemainCMC { get; set; }
        public int IsCMCExpired { get; set; }
        public int? RemainLicence { get; set; }
        public int IsLicenceExpired { get; set; }
        public int? RemainLicenceIR { get; set; }
        public int IsLicenceIRExpired { get; set; }
        public int? RemainProficiency { get; set; }
        public int IsProficiencyExpired { get; set; }
        public int? RemainProficiencyOPC { get; set; }
        public int IsProficiencyOPCExpired { get; set; }
        public int? RemainLPR { get; set; }
        public int IsLPRExpired { get; set; }
        public int? RemainMedical { get; set; }
        public int IsMedicalExpired { get; set; }
        public int? RemainSEPT { get; set; }
        public int IsSEPTExpired { get; set; }
        public int? RemainSEPTP { get; set; }
        public int IsSEPTPExpired { get; set; }
        public int? RemainDG { get; set; }
        public int IsDGExpired { get; set; }
        public int? RemainCRM { get; set; }
        public int IsCRMExpired { get; set; }
        public int? RemainCCRM { get; set; }
        public int IsCCRMExpired { get; set; }
        public int? RemainSMS { get; set; }
        public int IsSMSExpired { get; set; }
        public int? RemainAvSec { get; set; }
        public int IsAvSecExpired { get; set; }
        public int? RemainUpsetRecoveryTraining { get; set; }
        public int IsUpsetRecoveryTrainingExpired { get; set; }
        public int? RemainColdWeather { get; set; }
        public int IsColdWeatherExpired { get; set; }
        public int? RemainHotWeather { get; set; }
        public int IsHotWeatherExpired { get; set; }
        public string ScheduleName { get; set; }
        public string Code { get; set; }
        public DateTime DateInactiveBegin { get; set; }
        public DateTime DateInactiveEnd { get; set; }
        public string LinkedIn { get; set; }
        public string Telegram { get; set; }
        public string WhatsApp { get; set; }
        public int? AircraftTypeId { get; set; }
        public DateTime? DateTypeIssue { get; set; }
        public DateTime? DateTypeExpire { get; set; }
        public int? TypeRemain { get; set; }
        public DateTime? LineIssueDate { get; set; }
        public DateTime? LineExpireDate { get; set; }
        public DateTime? RecurrentIssueDate { get; set; }
        public DateTime? RecurrentExpireDate { get; set; }
        public int IsRecurrentExpired { get; set; }
        public int IsLineExpired { get; set; }
        public int IsTRIExpired { get; set; }
        public int IsTREExpired { get; set; }
        public int? RemainTRI { get; set; }
        public int? RemainTRE { get; set; }
        public int? RemainRecurrent { get; set; }
        public int? RemainLine { get; set; }
        public int? RemainEGPWS { get; set; }
        public double FlightSum { get; set; }
        public int FlightEarly { get; set; }
        public int FlightLate { get; set; }
        public bool? InActive { get; set; }
        public string JobGroupMain { get; set; }
        public string JobGroupMainCode { get; set; }
        public string JobGroupCode2 { get; set; }
        public string CodeX { get; set; }
        public int? RemainTypeMD { get; set; }
        public int? RemainType737 { get; set; }
        public int? RemainTypeAirbus { get; set; }
    }
}
